image : trestle/devops-base:latest

build:
  stage: build
  script: 
    - dotnet restore {{cookiecutter.library_name}}.sln
    - dotnet build --configuration Release 

test:
  stage: test
  script:
    - dotnet test {{cookiecutter.library_name}}.Test/{{cookiecutter.library_name}}.Test.csproj  --framework netcoreapp2.0

